"""scripts/set_version.sh stamps ONE version into all release files, idempotently.

Self-contained: synthesizes minimal fixtures for all release files (including the
Tauri files and lockfiles that workstream E owns) so this test is green regardless
of E's state.
"""

import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "scripts" / "set_version.sh"

PKG_JSON = (
    "{\n"
    '  "name": "university-helper-frontend",\n'
    '  "private": true,\n'
    '  "version": "0.0.0",\n'
    '  "dependencies": { "react": "^18.2.0", "jsqr": "^1.4.0" }\n'
    "}\n"
)
PKG_LOCK = (
    "{\n"
    '  "name": "university-helper-frontend",\n'
    '  "version": "0.0.0",\n'
    '  "lockfileVersion": 3,\n'
    '  "requires": true,\n'
    '  "packages": {\n'
    '    "": {\n'
    '      "name": "university-helper-frontend",\n'
    '      "version": "0.0.0",\n'
    '      "dependencies": { "react": "^18.2.0", "jsqr": "^1.4.0" }\n'
    "    },\n"
    '    "node_modules/jsqr": { "version": "1.4.0" }\n'
    "  }\n"
    "}\n"
)
UV_LOCK = (
    "version = 1\n\n"
    "[[package]]\n"
    'name = "typing-extensions"\n'
    'version = "0.0.0"\n\n'
    "[[package]]\n"
    'name = "university-helper-backend"\n'
    'version = "0.0.0"\n'
    'source = "registry+https://example.invalid/index"\n\n'
    "[[package]]\n"
    'name = "university-helper-backend"\n'
    'version = "0.0.0"\n'
    'source = { editable = "." }\n'
)
PYPROJECT = (
    "[project]\n"
    'name = "university-helper-backend"\n'
    'version = "0.0.0"\n'
    'requires-python = ">=3.11"\n\n'
    "[tool.ruff]\n"
    'target-version = "py311"\n'
)
MAIN_PY = (
    "app = FastAPI(\n"
    '    title="University Helper API",\n'
    '    description="…",\n'
    '    version="0.0.0",\n'
    '    docs_url="/docs",\n'
    ")\n"
)
TAURI_JSON = (
    "{\n"
    '  "productName": "University Helper",\n'
    '  "version": "0.0.0",\n'
    '  "identifier": "xyz.cornna.shuake"\n'
    "}\n"
)
CARGO_TOML = (
    "[package]\n"
    'name = "uh"\n'
    'version = "0.0.0"\n'
    'edition = "2021"\n\n'
    "[dependencies]\n"
    'tauri = { version = "2", features = [] }\n'
)
CARGO_LOCK = (
    "# This file is automatically @generated by Cargo.\n"
    "version = 3\n\n"
    "[[package]]\n"
    'name = "serde"\n'
    'version = "0.0.0"\n\n'
    "[[package]]\n"
    'name = "uh-desktop"\n'
    'version = "0.0.0"\n'
    'source = "registry+https://example.invalid/index"\n\n'
    "[[package]]\n"
    'name = "uh-desktop"\n'
    'version = "0.0.0"\n'
    "dependencies = [\n"
    ' "serde",\n'
    "]\n"
)

MANIFEST_FILES = [
    "frontend/package.json",
    "frontend/package-lock.json",
    "backend/pyproject.toml",
    "backend/app/main.py",
    "frontend/src-tauri/tauri.conf.json",
    "frontend/src-tauri/Cargo.toml",
]
LOCK_FILES = [
    "backend/uv.lock",
    "frontend/src-tauri/Cargo.lock",
]
FILES = MANIFEST_FILES + LOCK_FILES

NUMBER_WORDS = "zero one two three four five six seven eight nine ten".split()


def _parse_count(value: str) -> int:
    normalized = value.lower()
    return int(normalized) if normalized.isdigit() else NUMBER_WORDS.index(normalized)


def _make_tree(tmp: Path) -> None:
    (tmp / "scripts").mkdir()
    shutil.copy(SCRIPT, tmp / "scripts" / "set_version.sh")
    (tmp / "frontend" / "src-tauri").mkdir(parents=True)
    (tmp / "backend" / "app").mkdir(parents=True)
    (tmp / "frontend" / "package.json").write_text(PKG_JSON)
    (tmp / "frontend" / "package-lock.json").write_text(PKG_LOCK)
    (tmp / "backend" / "uv.lock").write_text(UV_LOCK)
    (tmp / "backend" / "pyproject.toml").write_text(PYPROJECT)
    (tmp / "backend" / "app" / "main.py").write_text(MAIN_PY)
    (tmp / "frontend" / "src-tauri" / "tauri.conf.json").write_text(TAURI_JSON)
    (tmp / "frontend" / "src-tauri" / "Cargo.toml").write_text(CARGO_TOML)
    (tmp / "frontend" / "src-tauri" / "Cargo.lock").write_text(CARGO_LOCK)


def _run(tmp: Path, version: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["bash", str(tmp / "scripts" / "set_version.sh"), version],
        check=True,
        capture_output=True,
        text=True,
    )


def test_stamps_all_release_files(tmp_path):
    _make_tree(tmp_path)
    _run(tmp_path, "9.9.9")
    assert json.loads((tmp_path / "frontend/package.json").read_text())["version"] == "9.9.9"
    package_lock = json.loads((tmp_path / "frontend/package-lock.json").read_text())
    assert package_lock["version"] == "9.9.9"
    assert package_lock["packages"][""]["version"] == "9.9.9"
    assert 'version = "9.9.9"' in (tmp_path / "backend/pyproject.toml").read_text()
    assert 'version="9.9.9"' in (tmp_path / "backend/app/main.py").read_text()
    assert json.loads((tmp_path / "frontend/src-tauri/tauri.conf.json").read_text())["version"] == "9.9.9"
    assert 'version = "9.9.9"' in (tmp_path / "frontend/src-tauri/Cargo.toml").read_text()
    uv_lock = (tmp_path / "backend/uv.lock").read_text()
    assert re.search(
        r'name = "university-helper-backend"\nversion = "9\.9\.9"\nsource = \{ editable = "\." \}',
        uv_lock,
    )
    cargo_lock = (tmp_path / "frontend/src-tauri/Cargo.lock").read_text()
    assert re.search(r'name = "uh-desktop"\nversion = "9\.9\.9"', cargo_lock)


def test_releasing_docs_match_set_version_manifest_contract():
    document = (REPO_ROOT / "docs" / "RELEASING.md").read_text(encoding="utf-8")
    match = re.search(
        r"stamps\s+it\s+into\s+all\s+(?P<total>\d+|[A-Za-z]+)\s+versioned\s+files—"
        r"(?P<manifest_count>\d+|[A-Za-z]+)\s+manifests\s+\((?P<manifests>[^)]+)\)\s+plus\s+"
        r"(?P<lock_count>\d+|[A-Za-z]+)\s+lockfiles\s+\((?P<locks>[^)]+)\)",
        document,
    )
    assert match, "RELEASING.md must list the set_version versioned-file contract"

    manifests = re.findall(r"`([^`]+)`", match.group("manifests"))
    locks = re.findall(r"`([^`]+)`", match.group("locks"))
    assert _parse_count(match.group("total")) == len(FILES)
    assert _parse_count(match.group("manifest_count")) == len(MANIFEST_FILES)
    assert _parse_count(match.group("lock_count")) == len(LOCK_FILES)
    assert manifests == MANIFEST_FILES
    assert locks == LOCK_FILES


def test_does_not_touch_dependency_versions(tmp_path):
    _make_tree(tmp_path)
    _run(tmp_path, "9.9.9")
    cargo = (tmp_path / "frontend/src-tauri/Cargo.toml").read_text()
    assert 'tauri = { version = "2"' in cargo  # dep spec untouched
    pkg = json.loads((tmp_path / "frontend/package.json").read_text())
    assert pkg["dependencies"]["react"] == "^18.2.0"  # dep spec untouched
    package_lock = json.loads((tmp_path / "frontend/package-lock.json").read_text())
    assert package_lock["packages"]["node_modules/jsqr"]["version"] == "1.4.0"
    uv_lock = (tmp_path / "backend/uv.lock").read_text()
    assert re.search(r'name = "typing-extensions"\nversion = "0\.0\.0"', uv_lock)
    assert re.search(
        r'name = "university-helper-backend"\nversion = "0\.0\.0"\nsource = "registry\+https://example\.invalid/index"',
        uv_lock,
    )
    cargo_lock = (tmp_path / "frontend/src-tauri/Cargo.lock").read_text()
    assert re.search(r'name = "serde"\nversion = "0\.0\.0"', cargo_lock)
    assert re.search(
        r'name = "uh-desktop"\nversion = "0\.0\.0"\nsource = "registry\+https://example\.invalid/index"',
        cargo_lock,
    )


def test_strips_leading_v(tmp_path):
    _make_tree(tmp_path)
    _run(tmp_path, "v1.4.0")
    assert json.loads((tmp_path / "frontend/package.json").read_text())["version"] == "1.4.0"


def test_idempotent(tmp_path):
    _make_tree(tmp_path)
    _run(tmp_path, "9.9.9")
    snap = {f: (tmp_path / f).read_text() for f in FILES}
    _run(tmp_path, "9.9.9")  # second run must be a no-op
    for f in FILES:
        assert (tmp_path / f).read_text() == snap[f], f"{f} changed on re-run"


def test_rejects_garbage_version(tmp_path):
    _make_tree(tmp_path)
    with pytest.raises(subprocess.CalledProcessError):
        _run(tmp_path, "not-a-version")
