<#
.SYNOPSIS
  Guided one-click deploy for University Helper on Windows (Docker Desktop).

.DESCRIPTION
  Generates a hardened .env (random secrets), pulls the prebuilt images (or
  builds from source with -Build), starts app + postgres + web via Docker
  Compose, waits for health, and prints the access URL. TLS/host-nginx setup is
  a Linux-server concern and is intentionally out of scope here — put this
  behind a reverse proxy (or use a Linux box with scripts/deploy_server.sh) for
  a public HTTPS deployment.

.EXAMPLE
  pwsh scripts/deploy_server.ps1 -Port 8080
.EXAMPLE
  pwsh scripts/deploy_server.ps1 -HostIp 192.168.1.50 -Build
#>
[CmdletBinding()]
param(
  [string]$Domain = "",
  [string]$HostIp = "",
  [int]$Port = 8080,
  [string]$Tag = "latest",
  [switch]$Build,
  [switch]$Yes
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$Project     = "university-helper"
$ComposeFile = "docker-compose.release.yml"
$ImageNs     = "ghcr.io/sweetcornna"
$BuildNpmReg = "https://registry.npmmirror.com"

function Info($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "[ok] $m" -ForegroundColor Green }
function Warn($m) { Write-Host "[!] $m"  -ForegroundColor Yellow }
function Die($m)  { Write-Host "[x] $m"  -ForegroundColor Red; exit 1 }
function Normalize-ImageTag([string]$RawTag) {
  if ([string]::IsNullOrWhiteSpace($RawTag)) { return "latest" }
  if ($RawTag -match '^v(?=\d)') { return $RawTag.Substring(1) }
  return $RawTag
}

function New-HexSecret([int]$Bytes = 32) {
  $b = New-Object byte[] $Bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
  ($b | ForEach-Object { $_.ToString('x2') }) -join ''
}
function New-FernetKey {
  # urlsafe-base64 of 32 random bytes == cryptography.fernet.Fernet.generate_key()
  $b = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
  ([Convert]::ToBase64String($b)).Replace('+', '-').Replace('/', '_')
}

$RawTag = $Tag
$ImageTag = Normalize-ImageTag $Tag
if ($ImageTag -ne $RawTag) {
  Warn "Normalizing release tag $RawTag -> $ImageTag for GHCR image tags."
}

Info "University Helper guided deploy (Windows) — mode: $(if ($Build) {'build'} else {'pull'}), tag: $ImageTag"

# ---- docker + compose -----------------------------------------------------
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Die "Docker not found. Install Docker Desktop (https://docs.docker.com/desktop/windows/) and re-run."
}
docker info *> $null
if ($LASTEXITCODE -ne 0) { Die "Docker Desktop is not running. Start it and re-run." }
docker compose version *> $null
if ($LASTEXITCODE -ne 0) { Die "Docker Compose v2 is required (ships with Docker Desktop)." }
function Compose { docker compose -p $Project -f $ComposeFile @args }
Ok "Docker + compose ready"

# ---- .env -----------------------------------------------------------------
if (Test-Path ".env") {
  Ok "Existing .env kept (delete it to regenerate secrets)."
} else {
  Info "Generating .env with fresh secrets…"
  if ($Domain) {
    $EnvTag = "production"; $Cors = "[`"https://$Domain`"]"
  } elseif ($HostIp) {
    $EnvTag = "dev"; $Cors = "[`"http://${HostIp}:$Port`"]"
    Warn "No -Domain: deploying http-only on ${HostIp}:$Port (ENV=dev)."
  } else {
    $EnvTag = "dev"; $Cors = "[`"http://localhost:$Port`",`"http://127.0.0.1:$Port`"]"
    Warn "No -Domain/-HostIp: deploying for local access only (http://localhost:$Port)."
  }
  $envBody = @"
# Generated by scripts/deploy_server.ps1 — do NOT commit. Back up
# CREDENTIAL_ENCRYPTION_KEY (losing it makes stored credentials unrecoverable).
POSTGRES_PASSWORD=$(New-HexSecret 24)
SECRET_KEY=$(New-HexSecret 32)
SHUAKE_COMPAT_SECRET=
CREDENTIAL_ENCRYPTION_KEY=$(New-FernetKey)
CORS_ORIGINS=$Cors
ENV=$EnvTag
APP_PORT=8000
HTTP_PORT=$Port
"@
  Set-Content -Path ".env" -Value $envBody -NoNewline -Encoding ascii
  Ok ".env written (ENV=$EnvTag, CORS=$Cors)"
}

# ---- bring up the stack ---------------------------------------------------
$env:HTTP_PORT = "$Port"
$env:APP_PORT  = "8000"
if ($Build) {
  Info "Building images from source (this can take a few minutes)…"
  docker build -f Dockerfile.server -t "$ImageNs/university-helper-app:local" .
  docker build -f Dockerfile.web --build-arg "NPM_REGISTRY=$BuildNpmReg" -t "$ImageNs/university-helper-web:local" .
  $env:UH_TAG = "local"
} else {
  $env:UH_TAG = $ImageTag
  Info "Pulling images $ImageNs/university-helper-{app,web}:$ImageTag…"
  Compose pull
}
Info "Starting stack…"
Compose up -d

# ---- health ---------------------------------------------------------------
$healthUrl = "http://127.0.0.1:$Port/health"
Info "Waiting for health at $healthUrl …"
$healthy = $false
foreach ($i in 1..60) {
  try {
    Invoke-WebRequest -UseBasicParsing -TimeoutSec 4 $healthUrl *> $null
    $healthy = $true; break
  } catch { Start-Sleep -Seconds 2 }
}
if ($healthy) { Ok "App is healthy." } else { Warn "Health check timed out. Check: docker compose -p $Project -f $ComposeFile logs --tail=80 app" }

# ---- summary --------------------------------------------------------------
Write-Host ""
Ok "Deploy complete."
if ($Domain)      { Write-Host "  Access:  https://$Domain  (front it with your own TLS reverse proxy)" }
elseif ($HostIp)  { Write-Host "  Access:  http://${HostIp}:$Port" }
else              { Write-Host "  Access:  http://localhost:$Port" }
Write-Host "  Manage:  docker compose -p $Project -f $ComposeFile ps | logs -f app | down"
